name: Main CI Pipeline

on:
  pull_request:
    branches:
      - develop
      - master
    paths:
      - "bfpy/**"
      - "tests/**"
      - "pyproject.toml"
      - "poetry.lock"
      - "setup.cfg"
      - "Earthfile"
      - ".github/workflows/main.yml"

jobs:
  pipeline:
    runs-on: ubuntu-latest
    env:
      GIT_URL_INSTEAD_OF: "https://github.com/=git@github.com:"
      FORCE_COLOR: 1
    steps:
      - uses: actions/checkout@v2

      - name: Put back the git branch into git (Earthly uses it for tagging)
        run: |
          branch=""
          if [ -n "$GITHUB_HEAD_REF" ]; then
            branch="$GITHUB_HEAD_REF"
          else
            branch="${GITHUB_REF##*/}"
          fi
          git checkout -b "$branch" || true

      - name: Download latest earth
        run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.3.10/earth-linux-amd64 -O /usr/local/bin/earth && chmod +x /usr/local/bin/earth'"

      - name: Earth version
        run: earth --version

      - name: Check type annotations
        run: earth +checkTypes

      - name: Run tests
        run: earth +runTests
